site_name: Gestion
fallback_url: http://localhost/
supported_domains:
  localhost:
    database:
      hostname: localhost
      username: root
      password:
      database:
    sellsy:
      access_token:
      access_token_secret:
      consumer_token:
      consumer_token_secret:
