SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `sellsy_clients` (
  `id` int (11) NOT NULL AUTO_INCREMENT,
  `sellsy_id` int (11) NOT NULL,
  `capital` text,
  `logo` text,
  `joindate` text,
  `auxCode` text,
  `accountingCode` text,
  `stickyNote` text,
  `ident` text,
  `rateCategory` text,
  `massmailingUnsubscribed` text,
  `massmailingUnsubscribedSMS` text,
  `phoningUnsubscribed` text,
  `massmailingUnsubscribedMail` text,
  `massmailingUnsubscribedCustom` text,
  `lastactivity` text,
  `ownerid` int (11),
  `type` text,
  `maincontactid` int (11),
  `relationType` text,
  `actif` text,
  `pic` text,
  `dateTransformProspect` text,
  `mainContactName` text,
  `name` text,
  `tel` text,
  `fax` text,
  `email` text,
  `mobile` text,
  `apenaf` text,
  `rcs` text,
  `siret` text,
  `siren` text,
  `vat` text,
  `mainaddressid` text,
  `maindelivaddressid` text,
  `web` text,
  `corpType` text,
  `addr_name` text,
  `addr_part1` text,
  `addr_part2` text,
  `addr_zip` text,
  `addr_town` text,
  `addr_state` text,
  `addr_lat` text,
  `addr_lng` text,
  `addr_countrycode` text,
  `delivaddr_name` text,
  `delivaddr_part1` text,
  `delivaddr_part2` text,
  `delivaddr_zip` text,
  `delivaddr_town` text,
  `delivaddr_state` text,
  `delivaddr_lat` text,
  `delivaddr_lng` text,
  `delivaddr_countrycode` text,
  `formated_joindate` text,
  `formated_transformprospectdate` text,
  `corpid` int (11),
  `lastactivity_formatted` text,
  `addr_countryname` text,
  `mainAddress` text,
  `addr_geocode` text,
  `delivaddr_countryname` text,
  `delivAddress` text,
  `delivaddr_geocode` text,
  `fullName` text,
  `contactId` text,
  `contactDetails` text,
  `formatted_tel` text,
  `formatted_mobile` text,
  `formatted_fax` text,
  `owner` text,
  `webUrl` text,
   PRIMARY KEY (`id`, `sellsy_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

COMMIT;
