SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

DROP TABLE IF EXISTS `sellsy_clients`;

CREATE TABLE `sellsy_clients` (
  `id` int (11) NOT NULL,
  `thirdid` int (11),
  `capital` text COLLATE utf8mb4_unicode_ci,
  `logo` text COLLATE utf8mb4_unicode_ci,
  `joindate` text COLLATE utf8mb4_unicode_ci,
  `auxCode` text COLLATE utf8mb4_unicode_ci,
  `accountingCode` text COLLATE utf8mb4_unicode_ci,
  `stickyNote` text COLLATE utf8mb4_unicode_ci,
  `ident` text COLLATE utf8mb4_unicode_ci,
  `rateCategory` text COLLATE utf8mb4_unicode_ci,
  `massmailingUnsubscribed` text COLLATE utf8mb4_unicode_ci,
  `massmailingUnsubscribedSMS` text COLLATE utf8mb4_unicode_ci,
  `phoningUnsubscribed` text COLLATE utf8mb4_unicode_ci,
  `massmailingUnsubscribedMail` text COLLATE utf8mb4_unicode_ci,
  `massmailingUnsubscribedCustom` text COLLATE utf8mb4_unicode_ci,
  `lastactivity` text COLLATE utf8mb4_unicode_ci,
  `ownerid` int (11),
  `type` text COLLATE utf8mb4_unicode_ci,
  `maincontactid` int (11),
  `relationType` text COLLATE utf8mb4_unicode_ci,
  `actif` text COLLATE utf8mb4_unicode_ci,
  `pic` text COLLATE utf8mb4_unicode_ci,
  `dateTransformProspect` text COLLATE utf8mb4_unicode_ci,
  `mainContactName` text COLLATE utf8mb4_unicode_ci,
  `name` text COLLATE utf8mb4_unicode_ci,
  `tel` text COLLATE utf8mb4_unicode_ci,
  `fax` text COLLATE utf8mb4_unicode_ci,
  `email` text COLLATE utf8mb4_unicode_ci,
  `mobile` text COLLATE utf8mb4_unicode_ci,
  `apenaf` text COLLATE utf8mb4_unicode_ci,
  `rcs` text COLLATE utf8mb4_unicode_ci,
  `siret` text COLLATE utf8mb4_unicode_ci,
  `siren` text COLLATE utf8mb4_unicode_ci,
  `vat` text COLLATE utf8mb4_unicode_ci,
  `mainaddressid` text COLLATE utf8mb4_unicode_ci,
  `maindelivaddressid` text COLLATE utf8mb4_unicode_ci,
  `web` text COLLATE utf8mb4_unicode_ci,
  `corpType` text COLLATE utf8mb4_unicode_ci,
  `addr_name` text COLLATE utf8mb4_unicode_ci,
  `addr_part1` text COLLATE utf8mb4_unicode_ci,
  `addr_part2` text COLLATE utf8mb4_unicode_ci,
  `addr_zip` text COLLATE utf8mb4_unicode_ci,
  `addr_town` text COLLATE utf8mb4_unicode_ci,
  `addr_state` text COLLATE utf8mb4_unicode_ci,
  `addr_lat` text COLLATE utf8mb4_unicode_ci,
  `addr_lng` text COLLATE utf8mb4_unicode_ci,
  `addr_countrycode` text COLLATE utf8mb4_unicode_ci,
  `delivaddr_name` text COLLATE utf8mb4_unicode_ci,
  `delivaddr_part1` text COLLATE utf8mb4_unicode_ci,
  `delivaddr_part2` text COLLATE utf8mb4_unicode_ci,
  `delivaddr_zip` text COLLATE utf8mb4_unicode_ci,
  `delivaddr_town` text COLLATE utf8mb4_unicode_ci,
  `delivaddr_state` text COLLATE utf8mb4_unicode_ci,
  `delivaddr_lat` text COLLATE utf8mb4_unicode_ci,
  `delivaddr_lng` text COLLATE utf8mb4_unicode_ci,
  `delivaddr_countrycode` text COLLATE utf8mb4_unicode_ci,
  `formated_joindate` text COLLATE utf8mb4_unicode_ci,
  `formated_transformprospectdate` text COLLATE utf8mb4_unicode_ci,
  `corpid` int (11),
  `lastactivity_formatted` text COLLATE utf8mb4_unicode_ci,
  `addr_countryname` text COLLATE utf8mb4_unicode_ci,
  `mainAddress` text COLLATE utf8mb4_unicode_ci,
  `addr_geocode` text COLLATE utf8mb4_unicode_ci,
  `delivaddr_countryname` text COLLATE utf8mb4_unicode_ci,
  `delivAddress` text COLLATE utf8mb4_unicode_ci,
  `delivaddr_geocode` text COLLATE utf8mb4_unicode_ci,
  `fullName` text COLLATE utf8mb4_unicode_ci,
  `contactId` text COLLATE utf8mb4_unicode_ci,
  `contactDetails` text COLLATE utf8mb4_unicode_ci,
  `formatted_tel` text COLLATE utf8mb4_unicode_ci,
  `formatted_mobile` text COLLATE utf8mb4_unicode_ci,
  `formatted_fax` text COLLATE utf8mb4_unicode_ci,
  `owner` text COLLATE utf8mb4_unicode_ci,
  `webUrl` text COLLATE utf8mb4_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `sellsy_clients` ADD PRIMARY KEY (`id`);
COMMIT;



